2019-10-24T11:58:50.332-0400 I CONTROL  [initandlisten] MongoDB starting : pid=7937 port=27017 dbpath=/scratch/achattor/mongodb_storage/trial 64-bit host=bhg0040.bluehive.circ.private
2019-10-24T11:58:50.332-0400 I CONTROL  [initandlisten] db version v3.4.10
2019-10-24T11:58:50.332-0400 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2019-10-24T11:58:50.332-0400 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2019-10-24T11:58:50.333-0400 I CONTROL  [initandlisten] allocator: tcmalloc
2019-10-24T11:58:50.333-0400 I CONTROL  [initandlisten] modules: none
2019-10-24T11:58:50.333-0400 I CONTROL  [initandlisten] build environment:
2019-10-24T11:58:50.333-0400 I CONTROL  [initandlisten]     distmod: rhel70
2019-10-24T11:58:50.333-0400 I CONTROL  [initandlisten]     distarch: x86_64
2019-10-24T11:58:50.333-0400 I CONTROL  [initandlisten]     target_arch: x86_64
2019-10-24T11:58:50.333-0400 I CONTROL  [initandlisten] options: { net: { port: 27017 }, storage: { dbPath: "/scratch/achattor/mongodb_storage/trial" } }
2019-10-24T11:58:50.420-0400 W -        [initandlisten] Detected unclean shutdown - /scratch/achattor/mongodb_storage/trial/mongod.lock is not empty.
2019-10-24T11:58:50.446-0400 I -        [initandlisten] Detected data files in /scratch/achattor/mongodb_storage/trial created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-10-24T11:58:50.446-0400 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2019-10-24T11:58:50.447-0400 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=63525M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2019-10-24T11:58:52.397-0400 I CONTROL  [initandlisten] 
2019-10-24T11:58:52.397-0400 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-10-24T11:58:52.397-0400 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-10-24T11:58:52.397-0400 I CONTROL  [initandlisten] 
2019-10-24T11:58:52.397-0400 I CONTROL  [initandlisten] 
2019-10-24T11:58:52.397-0400 I CONTROL  [initandlisten] ** WARNING: You are running on a NUMA machine.
2019-10-24T11:58:52.397-0400 I CONTROL  [initandlisten] **          We suggest launching mongod like this to avoid performance problems:
2019-10-24T11:58:52.397-0400 I CONTROL  [initandlisten] **              numactl --interleave=all mongod [other options]
2019-10-24T11:58:52.398-0400 I CONTROL  [initandlisten] 
2019-10-24T11:58:52.398-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2019-10-24T11:58:52.398-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-10-24T11:58:52.398-0400 I CONTROL  [initandlisten] 
2019-10-24T11:58:52.398-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2019-10-24T11:58:52.398-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-10-24T11:58:52.398-0400 I CONTROL  [initandlisten] 
2019-10-24T11:58:52.634-0400 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/scratch/achattor/mongodb_storage/trial/diagnostic.data'
2019-10-24T11:58:52.634-0400 I NETWORK  [thread1] waiting for connections on port 27017
2019-10-24T11:58:53.055-0400 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2019-10-24T11:59:06.332-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:47750 #1 (1 connection now open)
2019-10-24T11:59:06.338-0400 I NETWORK  [conn1] received client metadata from 192.168.5.40:47750 conn1: { driver: { name: "nodejs", version: "3.2.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "Node.js v6.12.3, LE, mongodb-core: 3.2.3" }
2019-10-24T11:59:36.192-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:47824 #2 (2 connections now open)
2019-10-24T11:59:36.192-0400 I NETWORK  [conn2] received client metadata from 192.168.5.40:47824 conn2: { driver: { name: "nodejs", version: "3.2.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "Node.js v6.12.3, LE, mongodb-core: 3.2.3" }
2019-10-24T11:59:36.200-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:47828 #3 (3 connections now open)
2019-10-24T11:59:36.200-0400 I NETWORK  [conn3] received client metadata from 192.168.5.40:47828 conn3: { driver: { name: "nodejs", version: "3.2.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "Node.js v6.12.3, LE, mongodb-core: 3.2.3" }
2019-10-24T12:09:32.250-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:48166 #4 (4 connections now open)
2019-10-24T12:09:32.254-0400 I NETWORK  [conn4] received client metadata from 192.168.5.40:48166 conn4: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-10-24T12:09:32.360-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:48168 #5 (5 connections now open)
2019-10-24T12:09:32.361-0400 I NETWORK  [conn5] received client metadata from 192.168.5.40:48168 conn5: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-10-24T12:09:32.467-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:48170 #6 (6 connections now open)
2019-10-24T12:09:32.467-0400 I NETWORK  [conn6] received client metadata from 192.168.5.40:48170 conn6: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-10-24T12:09:37.460-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:48174 #7 (7 connections now open)
2019-10-24T12:09:37.461-0400 I NETWORK  [conn7] received client metadata from 192.168.5.40:48174 conn7: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-10-24T12:10:36.115-0400 I -        [conn4] end connection 192.168.5.40:48166 (7 connections now open)
2019-10-24T12:10:36.115-0400 I -        [conn6] end connection 192.168.5.40:48170 (7 connections now open)
2019-10-24T12:10:36.115-0400 I -        [conn5] end connection 192.168.5.40:48168 (7 connections now open)
2019-10-24T12:10:36.115-0400 I -        [conn7] end connection 192.168.5.40:48174 (7 connections now open)
2019-10-24T12:14:24.790-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:48340 #8 (4 connections now open)
2019-10-24T12:14:24.800-0400 I NETWORK  [conn8] received client metadata from 192.168.5.40:48340 conn8: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-10-24T12:14:24.891-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:48342 #9 (5 connections now open)
2019-10-24T12:14:24.892-0400 I NETWORK  [conn9] received client metadata from 192.168.5.40:48342 conn9: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-10-24T12:14:24.974-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:48344 #10 (6 connections now open)
2019-10-24T12:14:24.983-0400 I NETWORK  [conn10] received client metadata from 192.168.5.40:48344 conn10: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-10-24T12:14:29.933-0400 I NETWORK  [thread1] connection accepted from 192.168.5.40:48350 #11 (7 connections now open)
2019-10-24T12:14:29.934-0400 I NETWORK  [conn11] received client metadata from 192.168.5.40:48350 conn11: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "3.10.0-957.1.3.el7.x86_64" }, platform: "CPython 3.7.2.final.0" }
2019-10-24T13:56:14.999-0400 I -        [conn8] end connection 192.168.5.40:48340 (7 connections now open)
2019-10-24T13:56:14.999-0400 I -        [conn11] end connection 192.168.5.40:48350 (7 connections now open)
2019-10-24T13:56:14.999-0400 I -        [conn9] end connection 192.168.5.40:48342 (7 connections now open)
2019-10-24T13:56:14.999-0400 I -        [conn10] end connection 192.168.5.40:48344 (7 connections now open)
2019-10-24T19:34:45.558-0400 I -        [conn1] end connection 192.168.5.40:47750 (3 connections now open)
2019-10-24T19:34:45.559-0400 I -        [conn2] end connection 192.168.5.40:47824 (2 connections now open)
2019-10-24T19:34:45.559-0400 I -        [conn3] end connection 192.168.5.40:47828 (1 connection now open)
